### ISSUE TITLE
Account cannot be created

### ISSUE THREAD

**Issue by litch** [juancgarza/Account-Api-Example#2]
I'm trying to run the first command that I said would be used to evaluate this project and it's giving me a 404. 

Am I doing something wrong here?

```
% curl -X POST localhost:3000/accounts
{"status":404,"error":"Not Found","exception":"#\u003cActionController::RoutingError: No route matches [POST] \"/accounts\"\u003e","traces":{"Application Trace":[],"Framework Trace":[{"id":0,"trace":"gems/bundler/gems/actionpack-5.0.4/lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'"},{"id":1,"trace":"gems/bundler/gems/actionpack-5.0.4/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"},{"id":2,"trace":"gems/bundler/gems/railties-5.0.4/lib/rails/rack/logger.rb:36:in `call_app'"},{"id":3,"trace":"gems/bundler/gems/railties-5.0.4/lib/rails/rack/logger.rb:24:in `block in call'"},{"id":4,"trace":"gems/bundler/gems/activesupport-5.0.4/lib/active_support/tagged_logging.rb:69:in `block in tagged'"},{"id":5,"trace":"gems/bundler/gems/activesupport-5.0.4/lib/active_support/tagged_logging.rb:26:in `tagged'"},{"id":6,"trace":"gems/bundler/gems/activesupport-5.0.4/lib/active_support/tagged_logging.rb:69:in `tagged'"},{"id":7,"trace":"gems/bundler/gems/railties-5.0.4/lib/rails/rack/logger.rb:24:in `call'"},{"id":8,"trace":"gems/bundler/gems/actionpack-5.0.4/lib/action_dispatch/middleware/request_id.rb:24:in `call'"},{"id":9,"trace":"gems/bundler/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'"},{"id":10,"trace":"gems/bundler/gems/activesupport-5.0.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'"},{"id":11,"trace":"gems/bundler/gems/actionpack-5.0.4/lib/action_dispatch/middleware/exec
```

**Comment by juancgarza** [comment]
Changed controllers and routing for it to run on **localhost:3000/accounts** and not run on **localhost:3000/api/accounts**, did not follow instructions on assignment.
